name = "progress"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

rules = [
  { type = "Data", globs = ["**/*.ttf"], fallthrough = true }
]

[site]
bucket = "./page/dist"